"""init

Revision ID: 264beb902c3a
Revises: 88ebb802d9c9
Create Date: 2024-07-22 10:59:22.072385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '264beb902c3a'
down_revision: Union[str, None] = '88ebb802d9c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_usuarios_descripcion'), 'tipos_usuarios', ['descripcion'], unique=False)
    op.create_index(op.f('ix_tipos_usuarios_nombre'), 'tipos_usuarios', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipos_usuarios_nombre'), table_name='tipos_usuarios')
    op.drop_index(op.f('ix_tipos_usuarios_descripcion'), table_name='tipos_usuarios')
    op.drop_table('tipos_usuarios')
    # ### end Alembic commands ###
