"""init

Revision ID: 88ebb802d9c9
Revises: cbfc8f2b3bbe
Create Date: 2024-07-22 10:57:05.618186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ebb802d9c9'
down_revision: Union[str, None] = 'cbfc8f2b3bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombres', sa.String(), nullable=True),
    sa.Column('apellidos', sa.String(), nullable=True),
    sa.Column('correo', sa.String(), nullable=True),
    sa.Column('contraseña', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_apellidos'), 'usuarios', ['apellidos'], unique=False)
    op.create_index(op.f('ix_usuarios_contraseña'), 'usuarios', ['contraseña'], unique=False)
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=False)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_nombres'), 'usuarios', ['nombres'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_nombres'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_contraseña'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_apellidos'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
